hello:
	@echo "------------------------------"
	@echo "Invoke hello"
	@echo "------------------------------"

	@stellar contract invoke \
		--id stellar_hp \
  		--source plato \
		--network testnet \
	  	-- \
	  	hello \
	  	--to PLATO

hello_admin:
	@echo "------------------------------"
	@echo "Invoke hello"
	@echo "------------------------------"

	@stellar contract invoke \
		--id stellar_hp \
  		--source ares \
		--network testnet \
	  	-- \
	  	hello_admin \
	  	--to ARES